//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceMiIngresoHitss.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public int Id_Categoria { get; set; }
        public string Nombre_categ { get; set; }
        public string Descripcion_categ { get; set; }
    }
}
