//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceMiIngresoHitss.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id_Empleado { get; set; }
        public string Nombre_emp { get; set; }
        public string Apellido_emp { get; set; }
        public decimal DNI_emp { get; set; }
        public string Telefono_emp { get; set; }
    }
}
