//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceMiIngresoHitss.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public int Id_Venta { get; set; }
        public float Total { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Empleado { get; set; }
        public System.DateTime Fecha_venta { get; set; }
        public Nullable<decimal> Descuento_venta { get; set; }
        public decimal IVA { get; set; }
    }
}
