//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HitssMVC.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMiIngresoHitss.Modelo")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Descripcion_proField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioUnitarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion_pro {
            get {
                return this.Descripcion_proField;
            }
            set {
                if ((object.ReferenceEquals(this.Descripcion_proField, value) != true)) {
                    this.Descripcion_proField = value;
                    this.RaisePropertyChanged("Descripcion_pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Categoria {
            get {
                return this.Id_CategoriaField;
            }
            set {
                if ((this.Id_CategoriaField.Equals(value) != true)) {
                    this.Id_CategoriaField = value;
                    this.RaisePropertyChanged("Id_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Producto {
            get {
                return this.Id_ProductoField;
            }
            set {
                if ((this.Id_ProductoField.Equals(value) != true)) {
                    this.Id_ProductoField = value;
                    this.RaisePropertyChanged("Id_Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario {
            get {
                return this.PrecioUnitarioField;
            }
            set {
                if ((this.PrecioUnitarioField.Equals(value) != true)) {
                    this.PrecioUnitarioField = value;
                    this.RaisePropertyChanged("PrecioUnitario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceMiIngresoHitss.Modelo")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Apellido_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal DNI_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direccion_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_cliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Telefono_cliField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido_cli {
            get {
                return this.Apellido_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Apellido_cliField, value) != true)) {
                    this.Apellido_cliField = value;
                    this.RaisePropertyChanged("Apellido_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DNI_cli {
            get {
                return this.DNI_cliField;
            }
            set {
                if ((this.DNI_cliField.Equals(value) != true)) {
                    this.DNI_cliField = value;
                    this.RaisePropertyChanged("DNI_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion_cli {
            get {
                return this.Direccion_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Direccion_cliField, value) != true)) {
                    this.Direccion_cliField = value;
                    this.RaisePropertyChanged("Direccion_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_Cliente {
            get {
                return this.Id_ClienteField;
            }
            set {
                if ((this.Id_ClienteField.Equals(value) != true)) {
                    this.Id_ClienteField = value;
                    this.RaisePropertyChanged("Id_Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_cli {
            get {
                return this.Nombre_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_cliField, value) != true)) {
                    this.Nombre_cliField = value;
                    this.RaisePropertyChanged("Nombre_cli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono_cli {
            get {
                return this.Telefono_cliField;
            }
            set {
                if ((object.ReferenceEquals(this.Telefono_cliField, value) != true)) {
                    this.Telefono_cliField = value;
                    this.RaisePropertyChanged("Telefono_cli");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertProducto", ReplyAction="http://tempuri.org/IService1/InsertProductoResponse")]
        bool InsertProducto(HitssMVC.ServiceReference.Producto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertProducto", ReplyAction="http://tempuri.org/IService1/InsertProductoResponse")]
        System.Threading.Tasks.Task<bool> InsertProductoAsync(HitssMVC.ServiceReference.Producto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        HitssMVC.ServiceReference.Producto[] GetProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductos", ReplyAction="http://tempuri.org/IService1/GetProductosResponse")]
        System.Threading.Tasks.Task<HitssMVC.ServiceReference.Producto[]> GetProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarProducto", ReplyAction="http://tempuri.org/IService1/BuscarProductoResponse")]
        HitssMVC.ServiceReference.Producto[] BuscarProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarProducto", ReplyAction="http://tempuri.org/IService1/BuscarProductoResponse")]
        System.Threading.Tasks.Task<HitssMVC.ServiceReference.Producto[]> BuscarProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProducto", ReplyAction="http://tempuri.org/IService1/UpdateProductoResponse")]
        int UpdateProducto(HitssMVC.ServiceReference.Producto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProducto", ReplyAction="http://tempuri.org/IService1/UpdateProductoResponse")]
        System.Threading.Tasks.Task<int> UpdateProductoAsync(HitssMVC.ServiceReference.Producto pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProducto", ReplyAction="http://tempuri.org/IService1/deleteProductoResponse")]
        int deleteProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteProducto", ReplyAction="http://tempuri.org/IService1/deleteProductoResponse")]
        System.Threading.Tasks.Task<int> deleteProductoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCliente", ReplyAction="http://tempuri.org/IService1/InsertClienteResponse")]
        bool InsertCliente(HitssMVC.ServiceReference.Cliente cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertCliente", ReplyAction="http://tempuri.org/IService1/InsertClienteResponse")]
        System.Threading.Tasks.Task<bool> InsertClienteAsync(HitssMVC.ServiceReference.Cliente cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientes", ReplyAction="http://tempuri.org/IService1/GetClientesResponse")]
        HitssMVC.ServiceReference.Cliente[] GetClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientes", ReplyAction="http://tempuri.org/IService1/GetClientesResponse")]
        System.Threading.Tasks.Task<HitssMVC.ServiceReference.Cliente[]> GetClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientesDelimitador", ReplyAction="http://tempuri.org/IService1/GetClientesDelimitadorResponse")]
        HitssMVC.ServiceReference.Cliente[] GetClientesDelimitador(int deliminador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientesDelimitador", ReplyAction="http://tempuri.org/IService1/GetClientesDelimitadorResponse")]
        System.Threading.Tasks.Task<HitssMVC.ServiceReference.Cliente[]> GetClientesDelimitadorAsync(int deliminador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarCliente", ReplyAction="http://tempuri.org/IService1/BuscarClienteResponse")]
        HitssMVC.ServiceReference.Cliente[] BuscarCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarCliente", ReplyAction="http://tempuri.org/IService1/BuscarClienteResponse")]
        System.Threading.Tasks.Task<HitssMVC.ServiceReference.Cliente[]> BuscarClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCliente", ReplyAction="http://tempuri.org/IService1/UpdateClienteResponse")]
        int UpdateCliente(HitssMVC.ServiceReference.Cliente cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCliente", ReplyAction="http://tempuri.org/IService1/UpdateClienteResponse")]
        System.Threading.Tasks.Task<int> UpdateClienteAsync(HitssMVC.ServiceReference.Cliente cli);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCliente", ReplyAction="http://tempuri.org/IService1/deleteClienteResponse")]
        int deleteCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/deleteCliente", ReplyAction="http://tempuri.org/IService1/deleteClienteResponse")]
        System.Threading.Tasks.Task<int> deleteClienteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : HitssMVC.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<HitssMVC.ServiceReference.IService1>, HitssMVC.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertProducto(HitssMVC.ServiceReference.Producto pro) {
            return base.Channel.InsertProducto(pro);
        }
        
        public System.Threading.Tasks.Task<bool> InsertProductoAsync(HitssMVC.ServiceReference.Producto pro) {
            return base.Channel.InsertProductoAsync(pro);
        }
        
        public HitssMVC.ServiceReference.Producto[] GetProductos() {
            return base.Channel.GetProductos();
        }
        
        public System.Threading.Tasks.Task<HitssMVC.ServiceReference.Producto[]> GetProductosAsync() {
            return base.Channel.GetProductosAsync();
        }
        
        public HitssMVC.ServiceReference.Producto[] BuscarProducto(int id) {
            return base.Channel.BuscarProducto(id);
        }
        
        public System.Threading.Tasks.Task<HitssMVC.ServiceReference.Producto[]> BuscarProductoAsync(int id) {
            return base.Channel.BuscarProductoAsync(id);
        }
        
        public int UpdateProducto(HitssMVC.ServiceReference.Producto pro) {
            return base.Channel.UpdateProducto(pro);
        }
        
        public System.Threading.Tasks.Task<int> UpdateProductoAsync(HitssMVC.ServiceReference.Producto pro) {
            return base.Channel.UpdateProductoAsync(pro);
        }
        
        public int deleteProducto(int id) {
            return base.Channel.deleteProducto(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteProductoAsync(int id) {
            return base.Channel.deleteProductoAsync(id);
        }
        
        public bool InsertCliente(HitssMVC.ServiceReference.Cliente cli) {
            return base.Channel.InsertCliente(cli);
        }
        
        public System.Threading.Tasks.Task<bool> InsertClienteAsync(HitssMVC.ServiceReference.Cliente cli) {
            return base.Channel.InsertClienteAsync(cli);
        }
        
        public HitssMVC.ServiceReference.Cliente[] GetClientes() {
            return base.Channel.GetClientes();
        }
        
        public System.Threading.Tasks.Task<HitssMVC.ServiceReference.Cliente[]> GetClientesAsync() {
            return base.Channel.GetClientesAsync();
        }
        
        public HitssMVC.ServiceReference.Cliente[] GetClientesDelimitador(int deliminador) {
            return base.Channel.GetClientesDelimitador(deliminador);
        }
        
        public System.Threading.Tasks.Task<HitssMVC.ServiceReference.Cliente[]> GetClientesDelimitadorAsync(int deliminador) {
            return base.Channel.GetClientesDelimitadorAsync(deliminador);
        }
        
        public HitssMVC.ServiceReference.Cliente[] BuscarCliente(int id) {
            return base.Channel.BuscarCliente(id);
        }
        
        public System.Threading.Tasks.Task<HitssMVC.ServiceReference.Cliente[]> BuscarClienteAsync(int id) {
            return base.Channel.BuscarClienteAsync(id);
        }
        
        public int UpdateCliente(HitssMVC.ServiceReference.Cliente cli) {
            return base.Channel.UpdateCliente(cli);
        }
        
        public System.Threading.Tasks.Task<int> UpdateClienteAsync(HitssMVC.ServiceReference.Cliente cli) {
            return base.Channel.UpdateClienteAsync(cli);
        }
        
        public int deleteCliente(int id) {
            return base.Channel.deleteCliente(id);
        }
        
        public System.Threading.Tasks.Task<int> deleteClienteAsync(int id) {
            return base.Channel.deleteClienteAsync(id);
        }
    }
}
